### ISSUE TITLE
project URL related to another repository

### ISSUE THREAD

**Issue by geromegrignon** [khaledosman/angular-realworld-example-app#1]
Hello,

The url to your implementation is the one from an old [project](https://github.com/gothinkster/angular-realworld-example-app).
Can you deploy your app (using Github Pages or a free hosting provider) and udpate your Readme and the description of your repository?

Thanks

**Comment by khaledosman** [comment]
Thanks, The readme demo link should now be updated with a new link automatically deployed to netlify.
