### ISSUE TITLE
Remove NSFW content

### ISSUE THREAD

**Issue by bwijayaw** [khaledosman/angular-realworld-example-app#2]
As a user putting together onboarding examples for developers, I want to use this codebase. However the NSFW content is a huge no-no and needs to be gone.

Please see attached screenshot. Either disable the Popular Tags section or add a filter to remove all NSFW tags and text.

<img width="1182" alt="Screen Shot 2021-09-09 at 2 30 35 PM" src="https://user-images.githubusercontent.com/76452698/132750782-8ed2eea7-2201-4bd0-a17b-e332be522dd5.png">

**Comment by bwijayaw** [comment]
Moved to original repo: https://github.com/gothinkster/angular-realworld-example-app/issues/206

**Comment by khaledosman** [comment]
Yea I don't think this is in scope for this project, that should rather be done on the backend which is done in another repo/project shared across most/all other real-world app frontends

**Comment by bwijayaw** [comment]
Appreciate the quick response. Looks like this topic has come up before in the [realworld](https://github.com/gothinkster/realworld/issues?q=is%3Aissue+is%3Aopen+nsfw)
