### ISSUE TITLE
LISENCE.txt file does not exist.

### ISSUE THREAD

**Issue by tanaka888** [khaledosman/angular-realworld-example-app#7]
Could you please add the LISENCE.txt.

**Comment by khaledosman** [comment]
why?

**Comment by tanaka888** [comment]
I would like to customize and redistribute this project. But I can not find the license information. The GitHub official guide says "As a best practice, we encourage you to include the license file with your project."
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository

**Comment by khaledosman** [comment]
done in https://github.com/khaledosman/angular-realworld-example-app/commit/8a7313b42f3c86c0274322e2499a35d6e2790056
